### ISSUE TITLE
KeyError: 'distortion'

### ISSUE THREAD

**Issue by 3togo** [dayjaby/dibr-rvs#2]
jc@jc-X230:~/git/dibr-rvs$ python gammas.py --rig blender_data/cameraSettings.json --rgb blender_data --depth blender_data --out blender_output --outfile blender_output/gammas.csv --method dibr 
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
[0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232]
Traceback (most recent call last):
  File "gammas.py", line 96, in <module>
    }) for x in xrange(xs) for y in xrange(ys)}
  File "gammas.py", line 96, in <dictcomp>
    }) for x in xrange(xs) for y in xrange(ys)}
KeyError: 'distortion'

**Comment by dayjaby** [comment]
Please pull the newest commit. Should work then.

In blender_data/cameraSettings.json you can change xs to [0, 5] and ys to [0, 1] if you want some quick results, which you can see in blender_output then.

**Comment by doris0428c** [comment]
an$ python gammas.py --rig blender_data/cameraSettings.json --rgb blender_data --depth blender_data --out blender_output --outfile blender_output/gammas.csv --method dibr
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
Traceback (most recent call last):
  File "gammas.py", line 96, in <module>
    }) for x in xrange(xs) for y in xrange(ys)}
  File "gammas.py", line 96, in <dictcomp>
    }) for x in xrange(xs) for y in xrange(ys)}
KeyError: 'camera_id'
